name: CI

on: pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2
        with:
          tofu_wrapper: false
      - run: tofu fmt -check -recursive
      - run: tofu init -backend=false
      - run: tofu validate
